name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      super_secret: ${{ secrets.AWS_ACCESS_KEY_ID }}
    steps:
      - run: aws --version
      - run: echo ${super_secret}

