name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.MY_SECERT }}

  dev-task:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo ${{ env.DESTINATION }}

  prod-task:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo ${{ env.DESTINATION }}