name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - env:
          super_secret: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: echo "$super_secret"

